print('hello world!')
print('Как тебя зовут?')
myName = input()
print('Хорошее имя, ' + myName)
print('Длина твоего имени:')
print(len(myName))
print('Сколько тебе лет?')
myAge = input()
print('Круто')